spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toDoListDB?createDatabaseIfNotExist=true
    username: root
    password: 1234

  sql:
    init:
      encoding: UTF-8
      schema-locations: classpath*:schema.sql
      mode: always
  jpa:
    hibernate:
      ## 실행 할 때마다 테이블 생성 있으면 지우고 생성 초기화라고 보면됨 싫으면 update로 변경
      ddl-auto: create